spring:
    datasource:
        druid:
            driver-class-name: com.mysql.cj.jdbc.Driver
            url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&serverTimezone=Asia/Shanghai&useSSL=false&nullNamePatternMatchesAll=true
            username: root
            password: 123456
            initial-size: 5
            max-active: 20
            min-idle: 5
            max-wait: 60000
            pool-prepared-statements: true
            max-pool-prepared-statement-per-connection-size: 20
            time-between-eviction-runs-millis: 60000
            min-evictable-idle-time-millis: 300000
            #Oracle需要打开注释
            #validation-query: SELECT 1 FROM DUAL
            test-while-idle: true
            test-on-borrow: false
            test-on-return: false
            stat-view-servlet:
                enabled: true
                url-pattern: /druid/*
                #login-username: admin
                #login-password: admin
            filter:
                stat:
                    log-slow-sql: true
                    slow-sql-millis: 1000
                    merge-sql: false
                wall:
                    config:
                        multi-statement-allow: true
#    data:
#        mongodb:
#            host:
#                127.0.0.1
#            port:
#                27017
#            database:
#                demo


#redis:
#    database: 0
#    host: 127.0.0.1
#    port: 6379
#    #password: 	# 密码（默认为空）
#    timeout: 6000  # 连接超时时长（毫秒）
#    jedis:
#        pool:
#            max-active: 20  # 连接池最大连接数（使用负值表示没有限制）
#            max-wait: -1      # 连接池最大阻塞等待时间（使用负值表示没有限制）
#            max-idle: 10      # 连接池中的最大空闲连接
#            min-idle: 5

AES:
    KEY: 1234567890abcdef


#condition:
#        rand:
#            type: boolean
#
#    aop:
#        #切换到CGLIB，默认false是jdk原生动态代理
#        proxy-target-class: true


xxl:
    job:
        admin:
            #xxl-job管理地址
            addresses: http://localhost:8080/xxl-job-admin
        #xxl-job执行器
        executor:
            ip:
            port: 9999
            logpath: E:\tianpu\data\job
            appname: plat-job
            #日志文件清除天数
            logretentiondays: 30
        accessToken: